### ISSUE TITLE
Fix failing pandokia tests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pyraf#33]
These two tests failed with similar error on `pembry` public. @jhunkeler , do you know why?

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38273319
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38273203

```
Traceback (most recent call last):
  File "/Users/shared/iraf_conda/bldtmp/porcelain.pkk9bc5SPq/porcelain/envs/public/lib/python2.7/site-packages/pandokia/helpers/runner_minipyt.py", line 583, in process_file
    module = imp.load_source( module_name, filename )
  File "site.py", line 703, in <module>
    main()
  File "site.py", line 694, in main
    execsitecustomize()
  File "site.py", line 548, in execsitecustomize
    import sitecustomize
  File "/Users/iraf/rtx/stsci_python/pyraf/.tmp/ssbvirt/ssbdev-osx/lib/python2.7/sitecustomize.py", line 13, in <module>
OSError: [Errno 2] No such file or directory: '/Users/shared/iraf_conda/bldtmp/porcelain.pkk9bc5SPq/porcelain/envs/public/python/lib/python2.7/site-packages'
```

**Comment by cdsontag** [comment]
I don't understand why there are any `` pyraf/.tmp`` test at all.  I didn't create them.  Are they somehow needed by the infrastructure?

**Comment by pllim** [comment]
No idea. If we don't need them, then please disable.

**Comment by cdsontag** [comment]
Don't "disable" but DELETE.  There is NO ".tmp/" dir in the test repo, so there should also be NO such dir on disk (see chronic discussion about us doing tests wrong by not starting with a fresh checkout each night).

**Comment by pllim** [comment]
I deleted it. That mysterious `.tmp` directory only exists on `pembry public` and nowhere else.
