### ISSUE TITLE
Cannot run pyraf without a terminal

### ISSUE THREAD

**Issue by olebole** [spacetelescope/pyraf#43]
I want to run pyraf non-interactively; f.e. as a test during an automated build. But even trying to import it does not work. The follwing minimal example:
```
from stsci.tools import capable
capable.OF_GRAPHICS = False
from pyraf import iraf
```
When running directly from the command line, it works. However, when I redirect the input, it does not:
```
$ python foo.py </dev/null
stty: 'standard input': Inappropriate ioctl for device
i: Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    from pyraf import iraf
  File "/usr/lib/python2.7/dist-packages/pyraf/__init__.py", line 126, in <module>
    iraf.Init(doprint=0, hush=1)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraffunctions.py", line 257, in Init
    userpkg.run(_doprint=0, _hush=hush, _save=1)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 359, in run
    self._run(redirKW, specialKW)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 1667, in _run
    self._runCode()
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 1470, in _runCode
    self._clFunction(*parList, **kw)
  File "<CL script clpackage.user>", line 32, in login
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 1220, in __getattr__
    return self._taskObj.getParam(paramname,native=1,mode="h",exact=1)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 564, in getParam
    exact=exact, prompt=prompt)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 616, in _getParValue
    field, native, mode="h", prompt=prompt)
  File "/usr/lib/python2.7/dist-packages/pyraf/iraftask.py", line 905, in _getParFromDict
    native=native,mode=pmode,prompt=prompt)
  File "/usr/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 367, in get
    if prompt: self._optionalPrompt(mode)
  File "/usr/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 643, in _optionalPrompt
    self.getWithPrompt()
  File "/usr/lib/python2.7/dist-packages/stsci/tools/basicpar.py", line 349, in getWithPrompt
    raise EOFError("EOF on parameter prompt")
EOFError: EOF on parameter prompt
```
This happens on Python 2.7 as well as on Python 3.6.

**Comment by olebole** [comment]
Oops, this was my fault - a wrong statement in my 'login.cl` that caused some input.
